# Docker compose for Database of project   
# This file is used to set up PostgresSQL for persisti data of pipeline.
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - ../.env
    ports:
      - "${DB_PORT}:5432"
# Jupyter Notebook Docker Compose for Web Access
# This notebook is used for Exploratory Data Analysis (EDA) and data visualization before exporting to Power BI.
  jupyter:
    build: .
    ports:
      - "8888:8888"
    env_file:
      - ./.env.notebook
    volumes:
      - ../notebooks:/home/jovyan/work
    command: "start-notebook.sh --NotebookApp.token=''"